#!/bin/bash
# Install box64_trace and box64_memleak so they're callable from $PATH.
#
# Default: system-wide install to /usr/local (uses sudo if needed).
# User install:        PREFIX=$HOME/.local ./install.sh
# Custom destination:  PREFIX=/opt ./install.sh
#
# Layout:
#   $PREFIX/bin/box64_trace, box64_memleak       # thin shell wrappers
#   $PREFIX/lib/box64-ebpf-tools/                # Python sources + web/ assets

set -eu

PREFIX="${PREFIX:-/usr/local}"
BINDIR="$PREFIX/bin"
LIBDIR="$PREFIX/lib/box64-ebpf-tools"

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

# Walk up the path to find the first existing ancestor; that's the one
# whose write permission decides whether sudo is needed.
writable_ancestor() {
    local p="$1"
    while [ ! -e "$p" ]; do
        p="$(dirname "$p")"
    done
    [ -w "$p" ]
}

if [ "$(id -u)" -eq 0 ] || writable_ancestor "$PREFIX"; then
    SUDO=""
elif command -v sudo >/dev/null 2>&1; then
    SUDO="sudo"
else
    echo "ERROR: $PREFIX is not writable and sudo is not available." >&2
    echo "       Re-run as root, or set PREFIX to a writable path." >&2
    exit 1
fi

echo "Installing box64-ebpf-tools"
echo "  PREFIX:  $PREFIX"
echo "  bindir:  $BINDIR"
echo "  libdir:  $LIBDIR"
echo

$SUDO install -d "$BINDIR" "$LIBDIR" "$LIBDIR/web" "$LIBDIR/web/js"

# Python sources
$SUDO install -m 0644 \
    "$REPO_DIR/box64_common.py" \
    "$REPO_DIR/box64_trace.py" \
    "$REPO_DIR/box64_memleak.py" \
    "$REPO_DIR/box64_web.py" \
    "$LIBDIR/"

# Web frontend assets
$SUDO install -m 0644 \
    "$REPO_DIR/web/index.html" \
    "$REPO_DIR/web/style.css" \
    "$REPO_DIR/web/LICENSE-kbox" \
    "$LIBDIR/web/"
$SUDO install -m 0644 "$REPO_DIR/web/js/"*.js "$LIBDIR/web/js/"

# Wrapper scripts. Use a generated shim instead of symlinks so the tools
# work even if the user later moves or deletes the source checkout.
for tool in box64_trace box64_memleak; do
    $SUDO tee "$BINDIR/$tool" > /dev/null <<EOF
#!/bin/sh
# Auto-generated by box64-ebpf-tools install.sh — DO NOT EDIT.
exec /usr/bin/env python3 "$LIBDIR/$tool.py" "\$@"
EOF
    $SUDO chmod 0755 "$BINDIR/$tool"
done

echo "Installed:"
echo "  $BINDIR/box64_trace"
echo "  $BINDIR/box64_memleak"
echo
echo "eBPF needs root, so invoke with sudo. Make sure $BINDIR is on the"
echo "sudo PATH (it usually is for /usr/local/bin)."
echo
echo "Quick start:"
echo "  sudo box64_trace -- box64 ./game.exe"
echo "  sudo box64_memleak -p \$(pgrep -n box64)"
